<div style="text-align: right">Cesar Aguirre, 04/05/2024</div>
<div style="text-align: right">Let's hope the page has not changed its structure since </div>

# UEFA Webscraping

In [1]:
# Let's start with the necessary imports

import re
import time
import os, sys
import unidecode
import numpy as np
import pandas as pd
import more_itertools as mit

from tqdm import tqdm
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [2]:
# Set up Selenium WebDriver for Chrome
options = webdriver.ChromeOptions()
# options.add_argument('--headless')

# Set up the driver
driver = webdriver.Chrome(options=options)

# Navigate to the website
year_of_interest = 2025

url = f"https://www.uefa.com/uefachampionsleague/history/seasons/{year_of_interest}/statistics/players/" 
driver.get(url)
headers = {'User-Agent': 'Mozilla/5.0'}

#### The following code block is the longest. It took between 5 - 10 minutes to run

In [3]:
# Let's have the browser scroll automatically
i=0

# The epoch number should be 70
epochs = 70 

with tqdm(total = epochs) as pbar:
    while i<=epochs:
        prev_page_source = driver.page_source
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(4) # This pauses the page for 4 seconds to let it load
        new_page_source = driver.page_source
        if new_page_source == prev_page_source:
            break # Stop scrolling if no new content is loaded
        i+=1
        pbar.update(1)

71it [05:34,  4.71s/it]

In [4]:
# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(driver.page_source, "html.parser")

In [5]:
# This part converts the variable soup into a string and puts it into an html document called Players
with open(os.path.join(os.path.abspath(".."),"Players2.html"),'w' ,encoding= 'utf-8') as file:
    file.write(str(soup))

In [6]:
# Create a RegEx for Numerical Data Extraction
elements = soup.find_all(class_="ag-cell-value")

In [7]:
# This will give us a list of all the numerical data 
data_numbers = [element.text for element in elements]

# Since there are 6 columns, we can split the data every 6 numbers.
sublists = list(mit.chunked(data_numbers, 8))         

sublists

[['01', 'PachoParis - Defender', '1542', '17', '0', '0', '159.2', '33.8'],
 ['02', 'HakimiParis - Defender', '1540', '17', '4', '5', '176.8', '36.9'],
 ['03',
  'Nuno MendesParis - Defender',
  '1449',
  '16',
  '4',
  '2',
  '145.4',
  '35.7'],
 ['04', 'VitinhaParis - Midfielder', '1448', '17', '2', '2', '180.2', '32.3'],
 ['05', 'MarquinhosParis - Defender', '1439', '16', '0', '0', '158.1', '33.2'],
 ['06',
  'João NevesParis - Midfielder',
  '1435',
  '17',
  '1',
  '1',
  '184.3',
  '31.7'],
 ['07',
  'DonnarummaParis - Goalkeeper',
  '1380',
  '15',
  '0',
  '0',
  '71.7',
  '26.1'],
 ['08', 'SommerInter - Goalkeeper', '1290', '14', '0', '0', '50.5', '25.2'],
 ['09',
  'KimmichBayern München - Midfielder',
  '1260',
  '14',
  '0',
  '6',
  '178.9',
  '32.2'],
 ['10',
  'ValverdeReal Madrid - Midfielder',
  '1236',
  '14',
  '0',
  '3',
  '140',
  '35.2'],
 ['11',
  'RaphinhaBarcelona - Forward',
  '1225',
  '14',
  '13',
  '9',
  '126.8',
  '34.7'],
 ['12',
  'RüdigerReal Madrid - Defender',
  '1188',
  '13',
  '2',
  '0',
  '123.7',
  '34.1'],
 ['13', 'RayaArsenal - Goalkeeper', '1170', '13', '0', '0', '86.3', '28.9'],
 ['13',
  'KobelB. Dortmund - Goalkeeper',
  '1170',
  '13',
  '0',
  '0',
  '57.7',
  '27.9'],
 ['15', 'DembéléParis - Forward', '1163', '15', '8', '6', '126.1', '33.9'],
 ['16',
  'Fabián RuizParis - Midfielder',
  '1151',
  '17',
  '1',
  '4',
  '144.7',
  '31.3'],
 ['17',
  'BellinghamReal Madrid - Midfielder',
  '1136',
  '13',
  '3',
  '2',
  '131.1',
  '33.9'],
 ['18',
  'MbappéReal Madrid - Forward',
  '1132',
  '14',
  '7',
  '2',
  '109.9',
  '36.4'],
 ['19',
  'KaneBayern München - Forward',
  '1120',
  '13',
  '11',
  '2',
  '139.4',
  '30.4'],
 ['20',
  'PedriBarcelona - Midfielder',
  '1117',
  '14',
  '0',
  '2',
  '141.1',
  '31.6'],
 ['21',
  'CourtoisReal Madrid - Goalkeeper',
  '1110',
  '12',
  '0',
  '0',
  '56.1',
  '25.7'],
 ['22', 'KoundéBarcelona - Defender', '1106', '13', '0', '3', '113.2', '33'],
 ['23',
  'Vinícius JúniorReal Madrid - Forward',
  '1104',
  '12',
  '8',
  '3',
  '118.9',
  '35.5'],
 ['24', 'YamalBarcelona - Forward', '1101', '13', '5', '3', '101.3', '32.2'],
 ['25', 'BarcolaParis - Forward', '1096', '17', '3', '4', '120.5', '35.6'],
 ['26',
  'GuirassyB. Dortmund - Forward',
  '1084',
  '14',
  '13',
  '4',
  '92.6',
  '32.5'],
 ['27',
  'VanakenClub Brugge - Midfielder',
  '1080',
  '12',
  '1',
  '1',
  '141.7',
  '30.3'],
 ['27', 'HanckoFeyenoord - Defender', '1080', '12', '1', '1', '119.9', '32.7'],
 ['27', 'OtamendiBenfica - Defender', '1080', '12', '1', '0', '116.8', '30.8'],
 ['27',
  'SchlotterbeckB. Dortmund - Defender',
  '1080',
  '12',
  '0',
  '1',
  '112',
  '32.9'],
 ['27',
  'MecheleClub Brugge - Defender',
  '1080',
  '12',
  '0',
  '0',
  '125.6',
  '32.3'],
 ['27',
  'MignoletClub Brugge - Goalkeeper',
  '1080',
  '12',
  '0',
  '0',
  '65.1',
  '27.2'],
 ['27',
  'E. MartínezAston Villa - Goalkeeper',
  '1080',
  '12',
  '0',
  '0',
  '61.9',
  '26.7'],
 ['27', 'TrubinBenfica - Goalkeeper', '1080', '12', '0', '0', '56', '27.4'],
 ['35',
  'De CuyperClub Brugge - Midfielder',
  '1079',
  '12',
  '1',
  '0',
  '131.8',
  '31.3'],
 ['36', 'BastoniInter - Defender', '1078', '14', '0', '1', '85.5', '32.5'],
 ['37', 'KimBayern München - Defender', '1074', '13', '1', '0', '126.6', '35'],
 ['38',
  'OrdoñezClub Brugge - Defender',
  '1048',
  '12',
  '0',
  '0',
  '112.3',
  '31.9'],
 ['39',
  'TielemansAston Villa - Midfielder',
  '1046',
  '12',
  '2',
  '3',
  '132.6',
  '31.1'],
 ['40',
  'OliseBayern München - Midfielder',
  '1033',
  '14',
  '5',
  '1',
  '134.6',
  '32.8'],
 ['41', 'RogersAston Villa - Forward', '1025', '12', '4', '3', '130', '33.8'],
 ['42', 'BenítezPSV - Goalkeeper', '1020', '11', '0', '0', '50.7', '26.6'],
 ['43', 'RiceArsenal - Midfielder', '1005', '13', '4', '2', '133', '34.2'],
 ['44',
  'Orkun KökçüBenfica - Midfielder',
  '995',
  '12',
  '4',
  '0',
  '120.7',
  '32.5'],
 ['45', 'BarellaInter - Midfielder', '994', '13', '0', '2', '97.4', '32.7'],
 ['46', 'AursnesBenfica - Midfielder', '990', '12', '0', '1', '141.8', '32.2'],
 ['46', 'KonsaAston Villa - Defender', '990', '11', '1', '0', '108', '34.3'],
 ['46',
  'UpamecanoBayern München - Defender',
  '990',
  '11',
  '0',
  '1',
  '121.3',
  '34.6'],
 ['46', 'SalibaArsenal - Defender', '990', '11', '0', '0', '110.1', '33'],
 ['50',
  'LewandowskiBarcelona - Forward',
  '985',
  '13',
  '11',
  '0',
  '92.5',
  '32.1'],
 ['51', 'CubarsíBarcelona - Defender', '981', '13', '0', '1', '94.3', '32.9'],
 ['52', 'DumfriesInter - Defender', '974', '12', '2', '3', '75.2', '34.5'],
 ['53',
  'Iñigo MartínezBarcelona - Defender',
  '958',
  '11',
  '2',
  '1',
  '101.7',
  '31.4'],
 ['54',
  'RyersonB. Dortmund - Defender',
  '956',
  '12',
  '0',
  '0',
  '97.9',
  '32.8'],
 ['55',
  'WellenreutherFeyenoord - Goalkeeper',
  '955',
  '11',
  '0',
  '0',
  '57.9',
  '26.7'],
 ['56', 'M. ThuramInter - Forward', '953', '14', '4', '1', '81.6', '33.8'],
 ['57',
  'JashariClub Brugge - Midfielder',
  '951',
  '11',
  '0',
  '0',
  '125.3',
  '32.6'],
 ['58', 'CanB. Dortmund - Defender', '940', '12', '2', '1', '90.3', '33.5'],
 ['59', 'TzolisClub Brugge - Forward', '939', '12', '1', '4', '116.4', '33.2'],
 ['59',
  'OnyedikaClub Brugge - Midfielder',
  '939',
  '11',
  '1',
  '1',
  '118.5',
  '29.9'],
 ['61', 'MartinelliArsenal - Forward', '935', '13', '2', '2', '113.3', '35.4'],
 ['62', 'OblakAtleti - Goalkeeper', '930', '10', '0', '0', '52.5', '24.1'],
 ['63',
  'Tomás AraújoBenfica - Defender',
  '927',
  '11',
  '0',
  '0',
  '106.5',
  '35.3'],
 ['64', 'PaixãoFeyenoord - Forward', '921', '11', '2', '4', '116.1', '34.1'],
 ['65',
  'GrossB. Dortmund - Midfielder',
  '918',
  '13',
  '1',
  '2',
  '106.4',
  '29.7'],
 ['66', 'BoscagliPSV - Defender', '913', '11', '0', '0', '93.9', '31.3'],
 ['67', 'PavardInter - Defender', '909', '12', '1', '0', '70.6', '31.8'],
 ['68', 'PavlidisBenfica - Forward', '905', '12', '7', '2', '115.3', '32.9'],
 ['68', 'L. de JongPSV - Forward', '905', '12', '2', '1', '98.5', '29.5'],
 ['70', 'CarrerasBenfica - Defender', '900', '10', '0', '2', '108', '33.3'],
 ['70', 'AlexsandroLille - Defender', '900', '10', '0', '1', '93', '32.9'],
 ['70', 'McGregorCeltic - Midfielder', '900', '10', '0', '0', '128.5', '32.5'],
 ['70', 'TahLeverkusen - Defender', '900', '10', '0', '0', '106.1', '33.8'],
 ['70', 'SchmeichelCeltic - Goalkeeper', '900', '10', '0', '0', '48.1', '24'],
 ['70', 'ChevalierLille - Goalkeeper', '900', '10', '0', '0', '43.1', '32.8'],
 ['76', 'ParteyArsenal - Midfielder', '899', '12', '0', '0', '109', '33.9'],
 ['77', 'MendyReal Madrid - Defender', '888', '11', '0', '1', '95.1', '33.9'],
 ['78', 'BrandtB. Dortmund - Midfielder', '884', '13', '0', '4', '91', '33.7'],
 ['79',
  'RodrygoReal Madrid - Forward',
  '880',
  '12',
  '5',
  '2',
  '102.9',
  '33.9'],
 ['80', 'De RoonAtalanta - Midfielder', '874', '10', '0', '1', '112', '33.1'],
 ['81',
  'GrimaldoLeverkusen - Defender',
  '871',
  '10',
  '2',
  '2',
  '112.2',
  '32.4'],
 ['82', 'ReijndersMilan - Midfielder', '870', '10', '3', '0', '111.3', '33.8'],
 ['83',
  'MusialaBayern München - Midfielder',
  '866',
  '12',
  '3',
  '4',
  '108',
  '34.1'],
 ['84', 'T. HernándezMilan - Defender', '861', '10', '0', '0', '99.8', '34.8'],
 ['84', 'MaignanMilan - Goalkeeper', '861', '10', '0', '0', '52.4', '30.3'],
 ['86', 'BakayokoPSV - Forward', '860', '12', '2', '1', '99.8', '34.5'],
 ['87', 'FlamingoPSV - Defender', '858', '11', '3', '0', '92.4', '32.1'],
 ['88', 'L. MartínezInter - Forward', '857', '14', '9', '0', '60', '32.3'],
 ['88', 'JutglàClub Brugge - Forward', '857', '12', '2', '2', '108.5', '32.9'],
 ['90', 'MkhitaryanInter - Midfielder', '856', '13', '0', '1', '81', '32.7'],
 ['91', 'KehrerMonaco - Defender', '855', '10', '1', '2', '87.6', '32.5'],
 ['91', 'DiakitéLille - Defender', '855', '10', '0', '0', '87.9', '32.1'],
 ['93',
  'Kerem AktürkoğluBenfica - Forward',
  '853',
  '12',
  '4',
  '0',
  '107.3',
  '32.9'],
 ['94', 'J. TimberArsenal - Defender', '852', '13', '1', '1', '92.5', '33.4'],
 ['95',
  'GittensB. Dortmund - Midfielder',
  '848',
  '14',
  '4',
  '0',
  '91.2',
  '34.9'],
 ['96',
  'SabitzerB. Dortmund - Midfielder',
  '845',
  '11',
  '0',
  '0',
  '100.5',
  '32.4'],
 ['97', 'Van DijkLiverpool - Defender', '840', '9', '1', '0', '87.5', '34.9'],
 ['98',
  'GoretzkaBayern München - Midfielder',
  '839',
  '12',
  '1',
  '1',
  '107',
  '32.2'],
 ['99',
  'A. JohnstonCeltic - Defender',
  '838',
  '10',
  '0',
  '0',
  '100.3',
  '34.6'],
 ['100',
  'ÇalhanoğluInter - Midfielder',
  '835',
  '12',
  '4',
  '2',
  '87.6',
  '33.6'],
 ['101', 'Mauro JúniorPSV - Defender', '829', '10', '0', '1', '90.6', '34.1'],
 ['102', 'BeelenFeyenoord - Defender', '827', '12', '0', '0', '97.4', '33'],
 ['103',
  'NeuerBayern München - Goalkeeper',
  '823',
  '10',
  '0',
  '0',
  '58',
  '25.6'],
 ['104',
  'XhakaLeverkusen - Midfielder',
  '819',
  '10',
  '0',
  '0',
  '105.7',
  '31.3'],
 ['105', 'MerinoArsenal - Midfielder', '818', '12', '2', '4', '113.6', '28.8'],
 ['106', 'TrustyCeltic - Defender', '816', '10', '0', '0', '97', '33.2'],
 ['107', 'GvardiolMan City - Defender', '815', '10', '0', '2', '98.9', '34.8'],
 ['108', 'AndréLille - Midfielder', '810', '9', '0', '0', '93.6', '30.2'],
 ['108', 'ChardonnetBrest - Defender', '810', '9', '0', '0', '87.4', '31.2'],
 ['108', 'BizotBrest - Goalkeeper', '810', '9', '0', '0', '49.6', '26.5'],
 ['108',
  'CarnesecchiAtalanta - Goalkeeper',
  '810',
  '9',
  '0',
  '0',
  '41.2',
  '29.6'],
 ['112', 'SalahLiverpool - Forward', '808', '9', '3', '4', '88.8', '34.5'],
 ['113',
  'AklioucheMonaco - Midfielder',
  '807',
  '10',
  '2',
  '2',
  '98.5',
  '33.4'],
 ['114', 'BaldeBarcelona - Defender', '804', '10', '0', '3', '86.2', '33.2'],
 ['114', 'GabrielArsenal - Defender', '804', '9', '1', '0', '90.6', '33.3'],
 ['116',
  'De JongBarcelona - Midfielder',
  '803',
  '13',
  '0',
  '0',
  '82.6',
  '31.9'],
 ['117', 'GattiJuventus - Defender', '801', '9', '0', '1', '81.5', '33.8'],
 ['118',
  'TchouaméniReal Madrid - Midfielder',
  '800',
  '11',
  '0',
  '0',
  '97',
  '33.3'],
 ['118', 'FofanaMilan - Midfielder', '800', '10', '0', '2', '98.2', '33.1'],
 ['120',
  'ØdegaardArsenal - Midfielder',
  '798',
  '11',
  '3',
  '1',
  '106.4',
  '32.2'],
 ['121', 'Rafael LeãoMilan - Forward', '797', '10', '3', '2', '84.9', '35.6'],
 ['122',
  'FrimpongLeverkusen - Defender',
  '796',
  '10',
  '0',
  '5',
  '89.7',
  '35.4'],
 ['123', 'KühnCeltic - Midfielder', '792', '10', '3', '1', '96.8', '35.9'],
 ['124',
  'Francisco TrincãoSporting CP - Forward',
  '791',
  '9',
  '0',
  '1',
  '96.9',
  '32.9'],
 ['125', 'AlvarezAtleti - Forward', '790', '10', '7', '1', '96.5', '34.3'],
 ['126', 'HatateCeltic - Defender', '788', '10', '1', '2', '105.4', '32.2'],
 ['127',
  'Hadj MoussaFeyenoord - Forward',
  '786',
  '11',
  '3',
  '0',
  '92.8',
  '32.8'],
 ['128',
  'GravenberchLiverpool - Midfielder',
  '784',
  '9',
  '0',
  '0',
  '95.5',
  '33.4'],
 ['129',
  'LaimerBayern München - Midfielder',
  '781',
  '11',
  '1',
  '1',
  '96.6',
  '34.4'],
 ['129', 'VandersonMonaco - Defender', '781', '9', '0', '1', '82.1', '33.9'],
 ['131',
  'HincapiéLeverkusen - Defender',
  '774',
  '9',
  '1',
  '0',
  '92.7',
  '34.8'],
 ['132', 'KiwiorArsenal - Defender', '772', '10', '0', '0', '91.7', '33.8'],
 ['133', 'HaalandMan City - Forward', '771', '9', '8', '0', '86.4', '36.6'],
 ['134', 'AcerbiInter - Defender', '770', '9', '1', '1', '76.5', '31.8'],
 ['135', 'TilPSV - Midfielder', '768', '12', '0', '2', '90.7', '32'],
 ['135', 'SeysClub Brugge - Midfielder', '768', '10', '0', '0', '97', '33.3'],
 ['137',
  'Bernardo SilvaMan City - Midfielder',
  '766',
  '9',
  '0',
  '0',
  '100.6',
  '30.6'],
 ['138', 'WirtzLeverkusen - Midfielder', '765', '9', '6', '1', '98', '33.6'],
 ['138',
  'MilamboFeyenoord - Midfielder',
  '765',
  '9',
  '3',
  '1',
  '100.9',
  '33.5'],
 ['138',
  'HjulmandSporting CP - Midfielder',
  '765',
  '9',
  '0',
  '0',
  '96.7',
  '31.4'],
 ['141', 'SakaArsenal - Forward', '763', '9', '6', '2', '86.7', '32.8'],
 ['142', 'MaedaCeltic - Forward', '761', '9', '4', '1', '98', '35.4'],
 ['143',
  'DiomandeSporting CP - Defender',
  '752',
  '9',
  '0',
  '0',
  '76.6',
  '34.3'],
 ['144', 'EmboloMonaco - Forward', '750', '10', '1', '3', '69.1', '32.9'],
 ['144', 'GiménezAtleti - Defender', '750', '8', '1', '0', '83.7', '33.1'],
 ['144',
  'SzczęsnyBarcelona - Goalkeeper',
  '750',
  '8',
  '0',
  '0',
  '34.8',
  '26.7'],
 ['147', 'De PaulAtleti - Midfielder', '748', '10', '0', '1', '93.4', '32.7'],
 ['147',
  'Raúl AsencioReal Madrid - Defender',
  '748',
  '10',
  '0',
  '1',
  '77.5',
  '35.8'],
 ['149', 'DigneAston Villa - Defender', '747', '9', '0', '0', '88.8', '31.1'],
 ['150', 'DavidLille - Forward', '746', '10', '7', '2', '85.3', '32.5'],
 ['151',
  'BensebainiB. Dortmund - Defender',
  '743',
  '12',
  '2',
  '1',
  '63.8',
  '33.2'],
 ['152', 'D. DouéParis - Forward', '742', '16', '5', '5', '91.2', '33.8'],
 ['153',
  'McGinnAston Villa - Midfielder',
  '739',
  '10',
  '3',
  '2',
  '89.6',
  '32.8'],
 ['153',
  'ÉdersonAtalanta - Midfielder',
  '739',
  '9',
  '1',
  '0',
  '100.2',
  '34.7'],
 ['155', 'KvaratskheliaParis - Forward', '735', '9', '3', '2', '78.7', '33.5'],
 ['156', 'GriezmannAtleti - Forward', '732', '10', '6', '3', '89.5', '30.9'],
 ['157', 'EngelsCeltic - Midfielder', '729', '10', '1', '3', '103.5', '32.3'],
 ['158', 'SaibariPSV - Midfielder', '728', '10', '3', '2', '78.7', '32.9'],
 ['159',
  'António SilvaBenfica - Defender',
  '724',
  '9',
  '0',
  '0',
  '81.9',
  '31.6'],
 ['160',
  'Geovany QuendaSporting CP - Forward',
  '722',
  '10',
  '0',
  '1',
  '87.3',
  '33.6'],
 ['161',
  'DjigaCrvena Zvezda - Defender',
  '720',
  '8',
  '1',
  '1',
  '74.7',
  '33.3'],
 ['161',
  'ElšnikCrvena Zvezda - Midfielder',
  '720',
  '8',
  '0',
  '2',
  '84.8',
  '33.7'],
 ['161', 'LalaBrest - Defender', '720', '8', '0', '0', '88.2', '32.4'],
 ['161', 'MatviyenkoShakhtar - Defender', '720', '8', '0', '0', '86', '33.8'],
 ['161', 'BondarShakhtar - Defender', '720', '8', '0', '0', '83.5', '33.5'],
 ['161', 'OrbánLeipzig - Defender', '720', '8', '0', '0', '72.8', '32.1'],
 ['161', 'VitíkSparta Praha - Defender', '720', '8', '0', '0', '72.3', '33.3'],
 ['161', 'MajeckiMonaco - Goalkeeper', '720', '8', '0', '0', '41.1', '28.3'],
 ['161', 'RiznykShakhtar - Goalkeeper', '720', '8', '0', '0', '40.1', '25.8'],
 ['161',
  'IsraelSporting CP - Goalkeeper',
  '720',
  '8',
  '0',
  '0',
  '39.2',
  '22.6'],
 ['161',
  'TakáčS. Bratislava - Goalkeeper',
  '720',
  '8',
  '0',
  '0',
  '38.7',
  '26.3'],
 ['161', 'EdersonMan City - Goalkeeper', '720', '8', '0', '0', '38.7', '27.9'],
 ['161',
  'VindahlSparta Praha - Goalkeeper',
  '720',
  '8',
  '0',
  '0',
  '37.4',
  '27'],
 ['174',
  'BlackmanS. Bratislava - Defender',
  '719',
  '8',
  '0',
  '0',
  '81.3',
  '33'],
 ['174',
  'Di GregorioJuventus - Goalkeeper',
  '719',
  '8',
  '0',
  '0',
  '34.1',
  '27'],
 ['176', 'SmalFeyenoord - Defender', '717', '11', '0', '1', '88.4', '31.5'],
 ['176',
  'FlorentinoBenfica - Midfielder',
  '717',
  '9',
  '0',
  '0',
  '99.2',
  '30.4'],
 ['178', 'TaremiInter - Forward', '715', '12', '1', '3', '74.2', '32.1'],
 ['179', 'BajrićS. Bratislava - Defender', '714', '8', '0', '0', '77.5', '34'],
 ['180',
  'KairinenSparta Praha - Midfielder',
  '713',
  '8',
  '2',
  '0',
  '82.4',
  '31.2'],
 ['181', 'CamaraBrest - Midfielder', '712', '10', '1', '1', '93.7', '35.1'],
 ['182', 'HienAtalanta - Defender', '710', '8', '0', '1', '80.4', '34.6'],
 ['183',
  'KashiaS. Bratislava - Defender',
  '709',
  '8',
  '0',
  '0',
  '74.5',
  '31.9'],
 ['184',
  'MittelstädtStuttgart - Defender',
  '706',
  '8',
  '0',
  '3',
  '86.7',
  '32.4'],
 ['185',
  'De KetelaereAtalanta - Forward',
  '702',
  '10',
  '4',
  '5',
  '84.5',
  '33.4'],
 ['185',
  'KamaraAston Villa - Midfielder',
  '702',
  '10',
  '0',
  '0',
  '86',
  '32.5'],
 ['185', 'SudakovShakhtar - Midfielder', '702', '8', '2', '1', '93.2', '32.7'],
 ['188',
  'YW SeolCrvena Zvezda - Defender',
  '701',
  '8',
  '0',
  '3',
  '79.6',
  '32.1'],
 ['189',
  'DaviesBayern München - Midfielder',
  '700',
  '9',
  '2',
  '0',
  '86.9',
  '35.6'],
 ['190', 'BisseckInter - Defender', '699', '13', '0', '0', '75.5', '32.9'],
 ['190',
  'ZappacostaAtalanta - Defender',
  '699',
  '9',
  '0',
  '5',
  '90.1',
  '33.3'],
 ['192', 'WatkinsAston Villa - Forward', '697', '12', '1', '4', '81.7', '33'],
 ['192', 'MagnettiBrest - Midfielder', '697', '10', '1', '1', '93.6', '29.9'],
 ['194',
  'StillerStuttgart - Midfielder',
  '695',
  '8',
  '1',
  '0',
  '90.5',
  '30.9'],
 ['195', 'LlorenteAtleti - Midfielder', '693', '8', '2', '4', '85.7', '35.3'],
 ['196',
  'AdeyemiB. Dortmund - Forward',
  '692',
  '10',
  '5',
  '1',
  '59.1',
  '35.3'],
 ['197', 'MillotStuttgart - Midfielder', '690', '8', '2', '4', '87.5', '31.2'],
 ['198', 'FodenMan City - Midfielder', '689', '9', '3', '1', '89.7', '33.3'],
 ['199', 'De VrijInter - Defender', '688', '9', '0', '0', '45.4', '32'],
 ['200', 'LangPSV - Forward', '686', '10', '2', '2', '72', '32.9'],
 ['201', 'OpendaLeipzig - Forward', '683', '8', '1', '3', '67.1', '35.5'],
 ['202', 'GloukhSalzburg - Midfielder', '681', '8', '0', '2', '81.3', '33'],
 ['203', 'DjimsitiAtalanta - Defender', '678', '9', '1', '0', '82.5', '31.2'],
 ['203',
  'Pau TorresAston Villa - Defender',
  '678',
  '9',
  '0',
  '1',
  '77.1',
  '31.8'],
 ['205',
  'Mac AllisterLiverpool - Midfielder',
  '674',
  '8',
  '2',
  '0',
  '87.9',
  '32.3'],
 ['205', 'StrelecS. Bratislava - Forward', '674', '8', '2', '0', '81.7', '33'],
 ['207',
  'LocatelliJuventus - Midfielder',
  '673',
  '9',
  '0',
  '0',
  '78.3',
  '29.8'],
 ['207', 'KryskivShakhtar - Midfielder', '673', '8', '0', '0', '85.1', '32'],
 ['209', 'TapsobaLeverkusen - Defender', '670', '9', '0', '1', '79.2', '33.3'],
 ['210',
  'BøvingSturm Graz - Midfielder',
  '669',
  '8',
  '0',
  '2',
  '90.4',
  '33.5'],
 ['211',
  'Kenan YıldızJuventus - Forward',
  '668',
  '10',
  '1',
  '1',
  '76.7',
  '34.2'],
 ['211',
  'KrunićCrvena Zvezda - Midfielder',
  '668',
  '8',
  '1',
  '2',
  '79.2',
  '31.2'],
 ['213',
  'PalaciosLeverkusen - Midfielder',
  '666',
  '10',
  '0',
  '0',
  '86.4',
  '31.1'],
 ['214',
  'TrossardArsenal - Midfielder',
  '665',
  '14',
  '2',
  '3',
  '89.5',
  '33.1'],
 ['215',
  'Carlos AugustoInter - Defender',
  '664',
  '13',
  '0',
  '2',
  '64',
  '34.1'],
 ['216', 'TraunerFeyenoord - Defender', '659', '9', '1', '1', '75.1', '31.9'],
 ['217',
  'KoopmeinersJuventus - Midfielder',
  '655',
  '9',
  '0',
  '0',
  '79.9',
  '31.6'],
 ['218', 'FernandesBrest - Midfielder', '651', '10', '1', '0', '84.6', '32.8'],
 ['219',
  'S. RistovskiGNK Dinamo - Defender',
  '650',
  '8',
  '0',
  '2',
  '79.2',
  '32.4'],
 ['220', 'KonatéLiverpool - Defender', '649', '7', '1', '0', '69.5', '34.1'],
 ['221',
  'ModrićReal Madrid - Midfielder',
  '647',
  '14',
  '0',
  '2',
  '77.4',
  '31.1'],
 ['221', 'BeukemaBologna - Defender', '647', '8', '0', '1', '76.7', '32'],
 ['223', 'AkanjiMan City - Defender', '646', '8', '0', '1', '72.1', '33.3'],
 ['223', 'ChabotStuttgart - Defender', '646', '8', '0', '0', '76', '32.4'],
 ['223', 'KaluluJuventus - Defender', '646', '8', '0', '0', '75.8', '34.5'],
 ['226', 'AjorqueBrest - Forward', '643', '8', '0', '3', '73.8', '32.3'],
 ['227', 'KolašinacAtalanta - Defender', '639', '9', '1', '1', '75.7', '32.9'],
 ['227', 'LewisMan City - Defender', '639', '9', '0', '1', '78.5', '32.5'],
 ['229',
  'SzoboszlaiLiverpool - Midfielder',
  '637',
  '9',
  '1',
  '1',
  '82.9',
  '34.5'],
 ['230', 'CoulibalyBrest - Defender', '635', '8', '0', '0', '69.3', '32.5'],
 ['231',
  'SanéBayern München - Midfielder',
  '634',
  '13',
  '1',
  '0',
  '75.6',
  '34.5'],
 ['232', 'Luis DíazLiverpool - Forward', '633', '9', '3', '0', '82.1', '33.2'],

### Now that we have the Data relatively structured, we can convert it into a dataframe

In [8]:
columns = ["Index", "Name, Team - Position ", "Minutes_played","Matches","Goals","Assists","Distance_covered","Top_speed"]
initial_data = pd.DataFrame(
    data = [i for i in sublists], 
    columns = columns,
    )

In [9]:
print(f'Initial Data Shape: {initial_data.shape}')
initial_data.head(5)

Initial Data Shape: (1107, 8)

,Index,"Name, Team - Position",Minutes_played,Matches,Goals,Assists,Distance_covered,Top_speed
0,01,PachoParis - Defender,1542,17,0,0,159.2,33.8
1,02,HakimiParis - Defender,1540,17,4,5,176.8,36.9
2,03,Nuno MendesParis - Defender,1449,16,4,2,145.4,35.7
3,04,VitinhaParis - Midfielder,1448,17,2,2,180.2,32.3
4,05,MarquinhosParis - Defender,1439,16,0,0,158.1,33.2

In [10]:
# Let's focus on columns 3 and onward
Numerical_Data = initial_data.iloc[:, 2:]

print(f'Numerical Data Shape: {Numerical_Data.shape}')
Numerical_Data.head(10)

Numerical Data Shape: (1107, 6)

  Minutes_played Matches Goals Assists Distance_covered Top_speed
0           1542      17     0       0            159.2      33.8
1           1540      17     4       5            176.8      36.9
2           1449      16     4       2            145.4      35.7
3           1448      17     2       2            180.2      32.3
4           1439      16     0       0            158.1      33.2
5           1435      17     1       1            184.3      31.7
6           1380      15     0       0             71.7      26.1
7           1290      14     0       0             50.5      25.2
8           1260      14     0       6            178.9      32.2
9           1236      14     0       3              140      35.2

### Great, now we have the numerical Data. Now, we'll take care of the corresponding players and their teams

In [11]:
# Let's create some lists for our DataFrame
player_name, team = [], []

for pk_identifier in soup.find_all(class_='pk-identifier'):
   
        primary_span   = pk_identifier.find('span', slot='primary')
        secondary_span = pk_identifier.find('span', slot='secondary')

        if primary_span and secondary_span:
            primary_text   = primary_span.get_text(strip=True)
            secondary_text = secondary_span.get_text(strip = True)

        # Concatenate with a space in between
        player_name.append(primary_text)
        team.append(secondary_text)

In [12]:
player_name

['Pacho',
 'Hakimi',
 'Nuno Mendes',
 'Vitinha',
 'Marquinhos',
 'João Neves',
 'Donnarumma',
 'Sommer',
 'Kimmich',
 'Valverde',
 'Raphinha',
 'Rüdiger',
 'Raya',
 'Kobel',
 'Dembélé',
 'Fabián Ruiz',
 'Bellingham',
 'Mbappé',
 'Kane',
 'Pedri',
 'Courtois',
 'Koundé',
 'Vinícius Júnior',
 'Yamal',
 'Barcola',
 'Guirassy',
 'Vanaken',
 'Hancko',
 'Otamendi',
 'Schlotterbeck',
 'Mechele',
 'Mignolet',
 'E. Martínez',
 'Trubin',
 'De Cuyper',
 'Bastoni',
 'Kim',
 'Ordoñez',
 'Tielemans',
 'Olise',
 'Rogers',
 'Benítez',
 'Rice',
 'Orkun Kökçü',
 'Barella',
 'Aursnes',
 'Konsa',
 'Upamecano',
 'Saliba',
 'Lewandowski',
 'Cubarsí',
 'Dumfries',
 'Iñigo Martínez',
 'Ryerson',
 'Wellenreuther',
 'M. Thuram',
 'Jashari',
 'Can',
 'Tzolis',
 'Onyedika',
 'Martinelli',
 'Oblak',
 'Tomás Araújo',
 'Paixão',
 'Gross',
 'Boscagli',
 'Pavard',
 'Pavlidis',
 'L. de Jong',
 'Carreras',
 'Alexsandro',
 'McGregor',
 'Tah',
 'Schmeichel',
 'Chevalier',
 'Partey',
 'Mendy',
 'Brandt',
 'Rodrygo',
 'De Roon',
 'Grimaldo',
 'Reijnders',
 'Musiala',
 'T. Hernández',
 'Maignan',
 'Bakayoko',
 'Flamingo',
 'L. Martínez',
 'Jutglà',
 'Mkhitaryan',
 'Kehrer',
 'Diakité',
 'Kerem Aktürkoğlu',
 'J. Timber',
 'Gittens',
 'Sabitzer',
 'Van Dijk',
 'Goretzka',
 'A. Johnston',
 'Çalhanoğlu',
 'Mauro Júnior',
 'Beelen',
 'Neuer',
 'Xhaka',
 'Merino',
 'Trusty',
 'Gvardiol',
 'André',
 'Chardonnet',
 'Bizot',
 'Carnesecchi',
 'Salah',
 'Akliouche',
 'Balde',
 'Gabriel',
 'De Jong',
 'Gatti',
 'Tchouaméni',
 'Fofana',
 'Ødegaard',
 'Rafael Leão',
 'Frimpong',
 'Kühn',
 'Francisco Trincão',
 'Alvarez',
 'Hatate',
 'Hadj Moussa',
 'Gravenberch',
 'Laimer',
 'Vanderson',
 'Hincapié',
 'Kiwior',
 'Haaland',
 'Acerbi',
 'Til',
 'Seys',
 'Bernardo Silva',
 'Wirtz',
 'Milambo',
 'Hjulmand',
 'Saka',
 'Maeda',
 'Diomande',
 'Embolo',
 'Giménez',
 'Szczęsny',
 'De Paul',
 'Raúl Asencio',
 'Digne',
 'David',
 'Bensebaini',
 'D. Doué',
 'McGinn',
 'Éderson',
 'Kvaratskhelia',
 'Griezmann',
 'Engels',
 'Saibari',
 'António Silva',
 'Geovany Quenda',
 'Djiga',
 'Elšnik',
 'Lala',
 'Matviyenko',
 'Bondar',
 'Orbán',
 'Vitík',
 'Majecki',
 'Riznyk',
 'Israel',
 'Takáč',
 'Ederson',
 'Vindahl',
 'Blackman',
 'Di Gregorio',
 'Smal',
 'Florentino',
 'Taremi',
 'Bajrić',
 'Kairinen',
 'Camara',
 'Hien',
 'Kashia',
 'Mittelstädt',
 'De Ketelaere',
 'Kamara',
 'Sudakov',
 'YW Seol',
 'Davies',
 'Bisseck',
 'Zappacosta',
 'Watkins',
 'Magnetti',
 'Stiller',
 'Llorente',
 'Adeyemi',
 'Millot',
 'Foden',
 'De Vrij',
 'Lang',
 'Openda',
 'Gloukh',
 'Djimsiti',
 'Pau Torres',
 'Mac Allister',
 'Strelec',
 'Locatelli',
 'Kryskiv',
 'Tapsoba',
 'Bøving',
 'Kenan Yıldız',
 'Krunić',
 'Palacios',
 'Trossard',
 'Carlos Augusto',
 'Trauner',
 'Koopmeiners',
 'Fernandes',
 'S. Ristovski',
 'Konaté',
 'Modrić',
 'Beukema',
 'Akanji',
 'Chabot',
 'Kalulu',
 'Ajorque',
 'Kolašinac',
 'Lewis',
 'Szoboszlai',
 'Coulibaly',
 'Sané',
 'Luis Díaz',
 'Pulišić',
 'Casadó',
 'Dedić',
 'Krejčí',
 'Lenglet',
 'Théophile-Catherine',
 'Spajić',
 'Nübel',
 'Skorupski',
 'Gazzaniga',
 'Araújo',
 'Monteiro',
 'Lavalée',
 'Baturina',
 'Silas',
 'Bouaddi',
 'Rouault',
 'Yalcouye',
 'Geertruida',
 'Nmecha',
 'Ndoye',
 'Beier',
 'Meunier',
 'Posch',
 'Baidoo',
 'Haïdara',
 'Kiteishvili',
 'Zakaria',
 'Camara',
 'Carter-Vickers',
 'Chukwuani',
 'Pašalić',
 'Francisco Conceição',
 'Gyökeres',
 'Zaïre-Emery',
 'Laçi',
 'Savvidis',
 'Ugrinic',
 'Q. Timber',
 'Haidara',
 'Anton',
 'Zieliński',
 'Savinho',
 'Golovin',
 'Alexander-Arnold',
 'Ledezma',
 'Taylor',
 'Retegui',
 'Lucas Vázquez',
 'C. Ndiaye',
 'Simeone',
 'Dimarco',
 'Alisson Becker',
 'Minamino',
 'IB Hwang',
 'Debast',
 'Mukau',
 'Schouten',
 'Lewis-Skelly',
 'Tomori',
 'Cambiaso',
 'Panák',
 'Havertz',
 'McKennie',
 'Weah',
 'Biereth',
 'Atakan Karazor',
 'Barseghyan',
 'Darmian',
 'Talbi',
 'Robertson',
 'Vlahović',
 'Gnabry',
 'Di María',
 'Bueno',
 'Veerman',
 'Vagnoman',
 'Ben Seghir',
 'Pavlović',
 'Gutiérrez',
 'Aiwu',
 'Torrente',
 'Kovář',
 'Gulácsi',
 'Scherpen',
 'Zubkov',
 'Pierre-Gabriel',
 'Tillman',
 'Bailey',
 'Matheus Nunes',
 'Lucumi',
 'Guerreiro',
 'Ryneš',
 'Gündoğan',
 'Šeško',
 'Ronald Araújo',
 'Nusa',
 'Lauper',
 'Cash',
 'Capaldo',
 'Sima',
 'Singo',
 'Freuler',
 'Wiesner',
 'Catamo',
 'Führich',
 'Bah',
 'Camara',
 'Camavinga',
 'Kulenović',
 'Frattesi',
 'Athekame',
 'Fabbian',
 'Birmančević',
 'Ganvoula',
 'Caio Henrique',
 'Gonçalo Inácio',
 'Nene',
 'Gudmundsson',
 'Thuram',
 'Diego Carlos',
 'Lookman',
 'Baumgartner',
 'Mišić',
 'Hadjam',
 'Brahim Díaz',
 'Piątkowski',
 'Salisu',
 'Henrichs',
 'Gallagher',
 'Bellanova',
 'Furuhashi',
 'Bernauer',
 'Núñez',
 'Konoplia',
 'Lee',
 'Bondarenko',
 'Coman',
 'Kevin',
 'Tolić',
 'Sahraoui',
 'Van de Beek',
 'Bryan Gil',
 'Baldé',
 'Galán',
 'Fermín López',
 'Rúben Dias',
 'Wimmer',
 'Gazibegović',
 'Iñaki Peña',
 'Nevistić',
 'Giménez',
 'Geyrhofer',
 'Gerard Martín',
 'Oriol Romeu',
 'Pedro Henrique',
 'Łakomy',
 'Tsimikas',
 'Blum',
 'Doumbia',
 'Olmo',
 'Matheus Reis',
 'Alejandro Francés',
 'Barrios',
 'Calafiori',
 'Molina',
 'Savona',
 'Undav',
 'Olatunji',
 'Bakker',
 'Ferran Torres',
 'Stanišić',
 'A. Maksimović',
 'Dams',
 'Martínez',
 'Musah',
 'Leweling',
 'Lino',
 'Dallinga',
 'Schjelderup',
 'Eguinaldo',
 'Schick',
 'Ceballos',
 'Seiwald',
 'Demirović',
 'Gabbia',
 'Koke',
 'Terzić',
 'De Bruyne',
 'Morata',
 'Daghim',
 'Ramsey',
 'Juanpe',
 'Danjuma',
 'Cabella',
 'Ueda',
 'Jatta',
 'Moro',
 'Blaswich',
 'Lukeba',
 'Lees-Melou',
 'Maatsen',
 'Morita',
 'Lykogiannis',
 'Mimović',
 'Müller',
 'Pereira Lage',
 'Scales',
 'Gakpo',
 'Skov Olsen',
 'David López',
 'Reinildo',
 'García',
 'Diambou',
 'González',
 'Stanković',
 'Stones',
 'Rog',
 'Zhegrova',
 'Mukiele',
 'Moder',
 'Sørensen',
 'Von Ballmoos',
 'Keller',
 'Kelleher',
 'Hrádecký',
 'Asllani',
 'Grealish',
 'Nieuwkoop',
 'Jones',
 'Svensson',
 'Johnston',
 'Iling-Junior',
 'Ivanić',
 'Pjaca',
 'Yeo',
 'Herrera',
 'Niasse',
 'Vermeeren',
 'Idah',
 'Castro',
 'Thiaw',
 'Simons',
 'A. Schlager',
 'White',
 'Bidstrup',
 'Karsdorp',
 'Perišić',
 'Martín',
 'Ihnatenko',
 'Marcelli',
 'Tella',
 'Tsygankov',
 'Clark',
 'Al. Rrahmani',
 'Benito',
 'Harder',
 'Orsolini',
 'Blind',
 'Jorginho',
 'Mandi',
 'Del Castillo',
 'Konaté',
 'Daniel Bragança',
 'Emerson',
 'Cuadrado',
 'Osman',
 'Calabria',
 'Mings',
 'Imeri',
 'Rashford',
 'Faivre',
 'Kovačić',
 'Colley',
 'Douglas Luiz',
 'Haraldsson',
 'Miranda',
 'Urbig',
 'L. Sadílek',
 'Gourna-Douath',
 'Gavi',
 'Abraham',
 'Virginius',
 'Duranville',
 'Sterling',
 'Ruggeri',
 'Zelený',
 'Dier',
 'Mawissa',
 'St. Juste',
 'Pavlović',
 'Samardžić',
 'Sørloth',
 'Marlon Gomes',
 'Ademi',
 'Ferguson',
 'Magassa',
 'Aké',
 'Zuberu',
 'Süle',
 'Blank',
 'Males',
 'Loftus-Cheek',
 'Walker',
 'Éder Militão',
 'Stuani',
 'Lotomba',
 'Wüthrich',
 'Bradley',
 'Eric García',
 'Chukwueze',
 'Miovski',
 'Reyna',
 'Andrich',
 'Onana',
 'Witsel',
 'S. Mmaee',
 'Zoukrou',
 'Preciado',
 'Guteša',
 'Zagorac',
 'Glazer',
 'Kolo Muani',
 'Bitshiabu',
 'Stojković',
 'Kossounou',
 'Fran García',
 'Raum',
 'Haraslín',
 'Sučić',
 'Correa',
 'Carranza',
 'Barreiro',
 'Asensio',
 'Kampl',
 'Obispo',
 'Fernandez-Pardo',
 'Jesus',
 'Le Cardinal',
 'Voet',
 'Kucka',
 'Olayinka',
 'Pobega',
 'Asprilla',
 'Read',
 'Boniface',
 'Amdouni',
 'Rieder',
 'Durán',
 'Sabbe',
 'Fresneda',
 'Paulo Bernardo',
 'Malen',
 'Diogo Jota',
 'João Simões',
 'Yan Couto',
 'Itten',
 'Danilo',
 'Le Normand',
 'Holm',
 'Quansah',
 'Ismaily',
 'Mbangula',
 'Ogiwara',
 'Nwaneri',
 'Malacia',
 'Sikan',
 'Casale',
 'Eduardo Quaresma',
 'Kačavenda',
 'Adli',
 'Urbański',
 'Tolói',
 'Diatta',
 'Valle',
 'Tobías',
 'Perin',
 'Kelly',
 'Gonçalo Ramos',
 'Fagioli',
 'Pedrinho',
 'Arnautović',
 'Bajcetic',
 'Mak',
 'Pedro Gonçalves',
 'Zinchenko',
 'Medveděv',
 'Petković',
 'Doku',
 'Horvat',
 'Špikić',
 'Malić',
 'Vetlesen',
 'Mitchell',
 'Dálcio Gomes',
 'João Félix',
 'Carvajal',
 'Ndiaye',
 'Vandevoordt',
 'Safonov',
 'Rui Silva',
 'Ortega',
 'Khudiakov',
 'Köhn',
 'Lunin',
 'M. Ilić',
 'Drkušić',
 'Ivanušec',
 'Nilsson',
 'Alaba',
 'João Palhinha',
 'Ricardo Esgaio',
 'Felício Milson',
 'Elliott',
 'Nuno Santos',
 'Pepi',
 'Azarov',
 'Gomes',
 'E. Krasniqi',
 'Cobbaut',
 'Cabal',
 'Radonjić',
 'Chase',
 'Dahl',
 'Metsoko',
 'Bruno Duarte',
 'Poulsen',
 'Yang',
 'Guindo',
 'Driouech',
 'Abel Ruiz',
 'Nagalo',
 'Keitel',
 'Weiss',
 'Renato Sanches',
 'Traoré',
 'Riquelme',
 'Arda Güler',
 'Lucas Beraldo',
 'Kanga',
 'Nielsen',
 'Endo',
 'Bogarde',
 'Touré',
 'Elia',
 'Bayo',
 'Endrick',
 'Zvonarek',
 'Ghram',
 'Stenzel',
 'Hofmann',
 'Camara',
 'Pešek',
 'Odgaard',
 'Hermoso',
 'Zaniolo',
 'Disasi',
 'Bijlow',
 'Brescianini',
 'Buendía',
 'Stepanenko',
 'Tierney',
 'Gomez',
 'Philogene',
 'Skóraś',
 'L. Hernández',
 'Tiago Santos',
 'Schlupp',
 'Azpilicueta',
 'Simpson-Pusey',
 'Ilenikhena',
 'Zerrouki',
 'Szöke',
 'Beste',
 'Arthur',
 'McAtee',
 'Chiesa',
 'Babadi',
 'Terrier',
 'Boey',
 'Okafor',
 'Renato Veiga',
 'Barkley',
 'Solís',
 'Kaboré',
 'Erencan Yardımcı',
 'Marmoush',
 'Bremer',
 'Portu',
 'Al-Dakhil',
 'Balogun',
 'Rollheiser',
 'Nadje',
 'Tel',
 'Ratkov',
 'Rodić',
 'Nico González',
 'Kjærgaard',
 'McConnell',
 'Land',
 'Rodri',
 'Ross',
 'Ševínský',
 'Zogbé',
 'A. Yaakobishvili',
 'Khusanov',
 'Meyer',
 'Da. Peretz',
 'Ravaglia',
 'Rui Patrício',
 'Bredlow',
 'J. Martínez',
 'Drommel',
 'Pau López',
 'Neto',
 'Ter Stegen',
 'Coudert',
 'Solbakken',
 'L. Ilić',
 'André Silva',
 'Jota',
 'Newertton',
 'Amavi',
 'Morgalla',
 'Danns',
 'Stengs',
 'Redmond',
 'Selvi Clua',
 'Mbappé',
 'Martin',
 'Chukwuemeka',
 'Cabral',
 'Bennacer',
 'Gabriel Teixeira',
 'Pavić',
 'Siquet',
 'Edwards',
 'Salah',
 'Teze',
 'Palestra',
 'Sliti',
 'Ralston',
 'Hoxha',
 'Forrest',
 'Terracciano',
 'Belotti',
 'Stergiou',
 'Vermant',
 'Al-Musrati',
 'Kawamura',
 'Pau Victor',
 'Fort',
 'McCowan',
 'Daněk',
 'Mayulu',
 'Zechiel',
 'Javi Serrano',
 'Alexandre Brito',
 'Mellberg',
 'Toure',
 'Erlić',
 'Ulreich',
 'Tuci',
 'Klostermann',
 'Fati',
 'Chaiwa',
 'Morton',
 'Torriani',
 'Zalewski',
 'Malanga',
 'Michal',
 'Camarda',
 'Dominguez',
 'Afonso Moreira',
 'Scalvini',
 'Palma',
 'Elmas',
 'H. Ito',
 'Lozano',
 'Hierländer',
 'Mustafić',
 'Romero',
 'João Rego',
 'Salih Özcan',
 'Nedeljković',
 'Aebischer',
 'Smith',
 'Bartesaghi',
 'Abdu Conté',
 'Nyoni',
 'Matazo',
 'Katai',
 'Ouedraogo',
 'Akpom',
 'Suchomel',
 'Adžić',
 'Ouattara',
 'Torre',
 'Franjić',
 'André Gomes',
 'Pfeiffer',
 'Oppegård',
 'Mbuku',
 'Stepanov',
 'Kimpembe',
 'Godfrey',
 'Meijer',
 'Córdoba',
 'Kuhn',
 'Gajdoš',
 'Campbell',
 'Onyeka',
 'De Pieri',
 'Belocian',
 'Kim',
 'Ramón',
 'Jastin García',
 'Pauschek',
 'Vojtko',
 'Pavelka',
 'Cummings',
 'Bajraktarević',
 'O’Reilly',
 'Gonzalez',
 'Lemar',
 'Prutsev',
 'Lucas Anjos',
 'Murray',
 'Berenbruch',
 'Christensen',
 'Cocchi',
 'Boakye',
 'Andres Cuenca',
 'Gebel',
 'Nallo',
 'Ibrahimović',
 'Aznou',
 'Corazza',
 'Rouhi',
 'Zagadou',
 'Azhil',
 'Schopp',
 'Lachaab',
 'Jakirović',
 'Grgic',
 'L. Penxa',
 'Butler-Oyedeji',
 'Carson',
 'Costarelli',
 'Lucas García',
 'Oriol Comas',
 'Cossier',
 'Karl',
 'Irie',
 'Campbell',
 'Pau García',
 'Danso',
 'Marc Aznar',
 'Juan Arango',
 'Olivier',
 'Cassa',
 'Raimund',
 'Jauny',
 'Irankunda',
 'Hawighorst',
 'Prestianni',
 'Sulemana',
 'Mateáš',
 'Camblan',
 'Isaac',
 'Comi',
 'Hödl',
 'Proctor',
 'Van Den Elshout',
 'Mikoláš',
 'Gauci',
 'Manzoni',
 'Diego Aguado',
 'Bujupi',
 'Mauro Couto',
 'Jetzer',
 'Bresser',
 'Toni Fernandez',
 'Landry Farré',
 'Gower',
 'Kacurri',
 'Porter',
 'Hudson',
 'Guille Fernández',
 'Ka',
 'James',
 'Tape',
 'Mbaye',
 'Benkara',
 'Daniel Yañez',
 'Voufack',
 'Sakar',
 'Dickes',
 'Re Cecconi',
 'Heaven',
 'Rosiak',
 'Kabia',
 'Robinson',
 'Plug',
 'Spina',
 'Wiener-Pucher',
 'Kiedl',
 'Zanchetta',
 'Baret',
 'Swinkels',
 'Smolenaars',
 'Uneken',
 'Young',
 'Nibombe',
 'Kusi-Asare',
 'Tincres',
 'Mikić',
 'Ćutuk',
 'Sorg',
 'Darvich',
 'Tiago Parente',
 'Zebić',
 'Bouabre',
 "Oulad M'Hand",
 'Kraaijeveld',
 'Klanac',
 'Eduardo Felicíssimo',
 'Denilson Santos',
 'Hugo Félix',
 'Gonçalo Oliveira',
 'Alajbegović',
 'Baković',
 'Lucas Dominguez',
 'Jovanović',
 'Meiser',
 'Zych',
 'Morrison',
 'Giersthove',
 'Berger',
 'Diop',
 'Coulibaly',
 'Bagnolini',
 'Wright',
 'Miguel Alves',
 'Zague',
 'El Hannach',
 'José Silva',
 'Rafael Nel',
 'Oelz',
 'Lukic',
 'Leandro Santos',
 'Bonnar',
 'Hugo De Llanos',
 'Chema Andrés',
 'González',
 'Lisewski',
 'Jatta',
 'Koß',
 'Schmitt',
 'Aidoo',
 'Motta',
 'Seiler',
 'Dema',
 'Bignetti',
 'Plam. Andreev',
 'Buchanan',
 'Ravaglioli',
 'Milosavljević',
 ...]

In [13]:
team

['Paris - Defender',
 'Paris - Defender',
 'Paris - Defender',
 'Paris - Midfielder',
 'Paris - Defender',
 'Paris - Midfielder',
 'Paris - Goalkeeper',
 'Inter - Goalkeeper',
 'Bayern München - Midfielder',
 'Real Madrid - Midfielder',
 'Barcelona - Forward',
 'Real Madrid - Defender',
 'Arsenal - Goalkeeper',
 'B. Dortmund - Goalkeeper',
 'Paris - Forward',
 'Paris - Midfielder',
 'Real Madrid - Midfielder',
 'Real Madrid - Forward',
 'Bayern München - Forward',
 'Barcelona - Midfielder',
 'Real Madrid - Goalkeeper',
 'Barcelona - Defender',
 'Real Madrid - Forward',
 'Barcelona - Forward',
 'Paris - Forward',
 'B. Dortmund - Forward',
 'Club Brugge - Midfielder',
 'Feyenoord - Defender',
 'Benfica - Defender',
 'B. Dortmund - Defender',
 'Club Brugge - Defender',
 'Club Brugge - Goalkeeper',
 'Aston Villa - Goalkeeper',
 'Benfica - Goalkeeper',
 'Club Brugge - Midfielder',
 'Inter - Defender',
 'Bayern München - Defender',
 'Club Brugge - Defender',
 'Aston Villa - Midfielder',
 'Bayern München - Midfielder',
 'Aston Villa - Forward',
 'PSV - Goalkeeper',
 'Arsenal - Midfielder',
 'Benfica - Midfielder',
 'Inter - Midfielder',
 'Benfica - Midfielder',
 'Aston Villa - Defender',
 'Bayern München - Defender',
 'Arsenal - Defender',
 'Barcelona - Forward',
 'Barcelona - Defender',
 'Inter - Defender',
 'Barcelona - Defender',
 'B. Dortmund - Defender',
 'Feyenoord - Goalkeeper',
 'Inter - Forward',
 'Club Brugge - Midfielder',
 'B. Dortmund - Defender',
 'Club Brugge - Forward',
 'Club Brugge - Midfielder',
 'Arsenal - Forward',
 'Atleti - Goalkeeper',
 'Benfica - Defender',
 'Feyenoord - Forward',
 'B. Dortmund - Midfielder',
 'PSV - Defender',
 'Inter - Defender',
 'Benfica - Forward',
 'PSV - Forward',
 'Benfica - Defender',
 'Lille - Defender',
 'Celtic - Midfielder',
 'Leverkusen - Defender',
 'Celtic - Goalkeeper',
 'Lille - Goalkeeper',
 'Arsenal - Midfielder',
 'Real Madrid - Defender',
 'B. Dortmund - Midfielder',
 'Real Madrid - Forward',
 'Atalanta - Midfielder',
 'Leverkusen - Defender',
 'Milan - Midfielder',
 'Bayern München - Midfielder',
 'Milan - Defender',
 'Milan - Goalkeeper',
 'PSV - Forward',
 'PSV - Defender',
 'Inter - Forward',
 'Club Brugge - Forward',
 'Inter - Midfielder',
 'Monaco - Defender',
 'Lille - Defender',
 'Benfica - Forward',
 'Arsenal - Defender',
 'B. Dortmund - Midfielder',
 'B. Dortmund - Midfielder',
 'Liverpool - Defender',
 'Bayern München - Midfielder',
 'Celtic - Defender',
 'Inter - Midfielder',
 'PSV - Defender',
 'Feyenoord - Defender',
 'Bayern München - Goalkeeper',
 'Leverkusen - Midfielder',
 'Arsenal - Midfielder',
 'Celtic - Defender',
 'Man City - Defender',
 'Lille - Midfielder',
 'Brest - Defender',
 'Brest - Goalkeeper',
 'Atalanta - Goalkeeper',
 'Liverpool - Forward',
 'Monaco - Midfielder',
 'Barcelona - Defender',
 'Arsenal - Defender',
 'Barcelona - Midfielder',
 'Juventus - Defender',
 'Real Madrid - Midfielder',
 'Milan - Midfielder',
 'Arsenal - Midfielder',
 'Milan - Forward',
 'Leverkusen - Defender',
 'Celtic - Midfielder',
 'Sporting CP - Forward',
 'Atleti - Forward',
 'Celtic - Defender',
 'Feyenoord - Forward',
 'Liverpool - Midfielder',
 'Bayern München - Midfielder',
 'Monaco - Defender',
 'Leverkusen - Defender',
 'Arsenal - Defender',
 'Man City - Forward',
 'Inter - Defender',
 'PSV - Midfielder',
 'Club Brugge - Midfielder',
 'Man City - Midfielder',
 'Leverkusen - Midfielder',
 'Feyenoord - Midfielder',
 'Sporting CP - Midfielder',
 'Arsenal - Forward',
 'Celtic - Forward',
 'Sporting CP - Defender',
 'Monaco - Forward',
 'Atleti - Defender',
 'Barcelona - Goalkeeper',
 'Atleti - Midfielder',
 'Real Madrid - Defender',
 'Aston Villa - Defender',
 'Lille - Forward',
 'B. Dortmund - Defender',
 'Paris - Forward',
 'Aston Villa - Midfielder',
 'Atalanta - Midfielder',
 'Paris - Forward',
 'Atleti - Forward',
 'Celtic - Midfielder',
 'PSV - Midfielder',
 'Benfica - Defender',
 'Sporting CP - Forward',
 'Crvena Zvezda - Defender',
 'Crvena Zvezda - Midfielder',
 'Brest - Defender',
 'Shakhtar - Defender',
 'Shakhtar - Defender',
 'Leipzig - Defender',
 'Sparta Praha - Defender',
 'Monaco - Goalkeeper',
 'Shakhtar - Goalkeeper',
 'Sporting CP - Goalkeeper',
 'S. Bratislava - Goalkeeper',
 'Man City - Goalkeeper',
 'Sparta Praha - Goalkeeper',
 'S. Bratislava - Defender',
 'Juventus - Goalkeeper',
 'Feyenoord - Defender',
 'Benfica - Midfielder',
 'Inter - Forward',
 'S. Bratislava - Defender',
 'Sparta Praha - Midfielder',
 'Brest - Midfielder',
 'Atalanta - Defender',
 'S. Bratislava - Defender',
 'Stuttgart - Defender',
 'Atalanta - Forward',
 'Aston Villa - Midfielder',
 'Shakhtar - Midfielder',
 'Crvena Zvezda - Defender',
 'Bayern München - Midfielder',
 'Inter - Defender',
 'Atalanta - Defender',
 'Aston Villa - Forward',
 'Brest - Midfielder',
 'Stuttgart - Midfielder',
 'Atleti - Midfielder',
 'B. Dortmund - Forward',
 'Stuttgart - Midfielder',
 'Man City - Midfielder',
 'Inter - Defender',
 'PSV - Forward',
 'Leipzig - Forward',
 'Salzburg - Midfielder',
 'Atalanta - Defender',
 'Aston Villa - Defender',
 'Liverpool - Midfielder',
 'S. Bratislava - Forward',
 'Juventus - Midfielder',
 'Shakhtar - Midfielder',
 'Leverkusen - Defender',
 'Sturm Graz - Midfielder',
 'Juventus - Forward',
 'Crvena Zvezda - Midfielder',
 'Leverkusen - Midfielder',
 'Arsenal - Midfielder',
 'Inter - Defender',
 'Feyenoord - Defender',
 'Juventus - Midfielder',
 'Brest - Midfielder',
 'GNK Dinamo - Defender',
 'Liverpool - Defender',
 'Real Madrid - Midfielder',
 'Bologna - Defender',
 'Man City - Defender',
 'Stuttgart - Defender',
 'Juventus - Defender',
 'Brest - Forward',
 'Atalanta - Defender',
 'Man City - Defender',
 'Liverpool - Midfielder',
 'Brest - Defender',
 'Bayern München - Midfielder',
 'Liverpool - Forward',
 'Milan - Forward',
 'Barcelona - Defender',
 'Salzburg - Defender',
 'Girona - Defender',
 'Atleti - Defender',
 'GNK Dinamo - Defender',
 'Crvena Zvezda - Defender',
 'Stuttgart - Goalkeeper',
 'Bologna - Goalkeeper',
 'Girona - Goalkeeper',
 'Sporting CP - Midfielder',
 'Young Boys - Forward',
 'Sturm Graz - Defender',
 'GNK Dinamo - Midfielder',
 'Crvena Zvezda - Forward',
 'Lille - Midfielder',
 'Stuttgart - Defender',
 'Sturm Graz - Midfielder',
 'Leipzig - Defender',
 'B. Dortmund - Midfielder',
 'Bologna - Forward',
 'B. Dortmund - Forward',
 'Lille - Defender',
 'Atalanta - Defender',
 'Salzburg - Defender',
 'Brest - Defender',
 'Sturm Graz - Midfielder',
 'Monaco - Midfielder',
 'Monaco - Midfielder',
 'Celtic - Defender',
 'Sturm Graz - Midfielder',
 'Atalanta - Midfielder',
 'Juventus - Forward',
 'Sporting CP - Forward',
 'Paris - Midfielder',
 'Sparta Praha - Midfielder',
 'S. Bratislava - Midfielder',
 'Young Boys - Midfielder',
 'Feyenoord - Midfielder',
 'Leipzig - Midfielder',
 'B. Dortmund - Defender',
 'Inter - Midfielder',
 'Man City - Midfielder',
 'Monaco - Midfielder',
 'Liverpool - Defender',
 'PSV - Midfielder',
 'Celtic - Defender',
 'Atalanta - Forward',
 'Real Madrid - Defender',
 'Crvena Zvezda - Forward',
 'Atleti - Forward',
 'Inter - Defender',
 'Liverpool - Goalkeeper',
 'Monaco - Midfielder',
 'Feyenoord - Midfielder',
 'Sporting CP - Defender',
 'Lille - Midfielder',
 'PSV - Midfielder',
 'Arsenal - Midfielder',
 'Milan - Defender',
 'Juventus - Defender',
 'Sparta Praha - Defender',
 'Arsenal - Midfielder',
 'Juventus - Midfielder',
 'Juventus - Midfielder',
 'Monaco - Forward',
 'Stuttgart - Midfielder',
 'S. Bratislava - Midfielder',
 'Inter - Defender',
 'Club Brugge - Midfielder',
 'Liverpool - Defender',
 'Juventus - Forward',
 'Bayern München - Forward',
 'Benfica - Forward',
 'Feyenoord - Defender',
 'PSV - Midfielder',
 'Stuttgart - Defender',
 'Monaco - Midfielder',
 'Milan - Defender',
 'Girona - Defender',
 'Sturm Graz - Defender',
 'GNK Dinamo - Defender',
 'Leverkusen - Goalkeeper',
 'Leipzig - Goalkeeper',
 'Sturm Graz - Goalkeeper',
 'Shakhtar - Midfielder',
 'GNK Dinamo - Defender',
 'PSV - Midfielder',
 'Aston Villa - Forward',
 'Man City - Midfielder',
 'Bologna - Defender',
 'Bayern München - Defender',
 'Sparta Praha - Defender',
 'Man City - Midfielder',
 'Leipzig - Forward',
 'Barcelona - Defender',
 'Leipzig - Midfielder',
 'Young Boys - Midfielder',
 'Aston Villa - Defender',
 'Salzburg - Midfielder',
 'Brest - Forward',
 'Monaco - Defender',
 'Bologna - Midfielder',
 'Sparta Praha - Defender',
 'Sporting CP - Forward',
 'Stuttgart - Midfielder',
 'Benfica - Defender',
 'Young Boys - Defender',
 'Real Madrid - Midfielder',
 'GNK Dinamo - Forward',
 'Inter - Midfielder',
 'Young Boys - Defender',
 'Bologna - Midfielder',
 'Sparta Praha - Midfielder',
 'Young Boys - Forward',
 'Monaco - Defender',
 'Sporting CP - Defender',
 'Salzburg - Forward',
 'Lille - Defender',
 'Juventus - Midfielder',
 'Aston Villa - Defender',
 'Atalanta - Forward',
 'Leipzig - Midfielder',
 'GNK Dinamo - Midfielder',
 'Young Boys - Defender',
 'Real Madrid - Forward',
 'Salzburg - Defender',
 'Monaco - Defender',
 'Leipzig - Defender',
 'Atleti - Midfielder',
 'Atalanta - Defender',
 'Celtic - Midfielder',
 'GNK Dinamo - Defender',
 'Liverpool - Forward',
 'Shakhtar - Defender',
 'Paris - Midfielder',
 'Shakhtar - Midfielder',
 'Bayern München - Forward',
 'Shakhtar - Midfielder',
 'S. Bratislava - Midfielder',
 'Lille - Midfielder',
 'Girona - Midfielder',
 'Girona - Forward',
 'Brest - Forward',
 'Atleti - Defender',
 'Barcelona - Forward',
 'Man City - Defender',
 'S. Bratislava - Defender',
 'Sturm Graz - Defender',
 'Barcelona - Goalkeeper',
 'GNK Dinamo - Goalkeeper',
 'Milan - Forward',
 'Sturm Graz - Defender',
 'Barcelona - Defender',
 'Girona - Midfielder',
 'Shakhtar - Defender',
 'Young Boys - Midfielder',
 'Liverpool - Defender',
 'Young Boys - Defender',
 'Brest - Midfielder',
 'Barcelona - Forward',
 'Sporting CP - Defender',
 'Girona - Defender',
 'Atleti - Midfielder',
 'Arsenal - Defender',
 'Atleti - Defender',
 'Juventus - Defender',
 'Stuttgart - Forward',
 'Sparta Praha - Forward',
 'Lille - Midfielder',
 'Barcelona - Forward',
 'Bayern München - Defender',
 'Crvena Zvezda - Midfielder',
 'PSV - Defender',
 'Girona - Defender',
 'Milan - Midfielder',
 'Stuttgart - Forward',
 'Atleti - Midfielder',
 'Bologna - Forward',
 'Benfica - Forward',
 'Shakhtar - Forward',
 'Leverkusen - Forward',
 'Real Madrid - Midfielder',
 'Leipzig - Midfielder',
 'Stuttgart - Midfielder',
 'Milan - Defender',
 'Atleti - Midfielder',
 'Salzburg - Defender',
 'Man City - Midfielder',
 'Milan - Forward',
 'Salzburg - Forward',
 'Aston Villa - Midfielder',
 'Girona - Defender',
 'Girona - Midfielder',
 'Lille - Midfielder',
 'Feyenoord - Forward',
 'Sturm Graz - Forward',
 'Bologna - Midfielder',
 'Salzburg - Goalkeeper',
 'Leipzig - Defender',
 'Brest - Midfielder',
 'Aston Villa - Defender',
 'Sporting CP - Midfielder',
 'Bologna - Defender',
 'Crvena Zvezda - Defender',
 'Bayern München - Forward',
 'Brest - Forward',
 'Celtic - Defender',
 'Liverpool - Forward',
 'Club Brugge - Forward',
 'Girona - Defender',
 'Atleti - Defender',
 'Leverkusen - Midfielder',
 'Salzburg - Midfielder',
 'Juventus - Forward',
 'Sturm Graz - Midfielder',
 'Man City - Defender',
 'GNK Dinamo - Midfielder',
 'Lille - Forward',
 'Leverkusen - Defender',
 'Feyenoord - Midfielder',
 'Sparta Praha - Defender',
 'Young Boys - Goalkeeper',
 'Young Boys - Goalkeeper',
 'Liverpool - Goalkeeper',
 'Leverkusen - Goalkeeper',
 'Inter - Midfielder',
 'Man City - Midfielder',
 'Feyenoord - Defender',
 'Liverpool - Midfielder',
 'B. Dortmund - Defender',
 'Sturm Graz - Defender',
 'Bologna - Midfielder',
 'Crvena Zvezda - Midfielder',
 'GNK Dinamo - Forward',
 'Salzburg - Midfielder',
 'Girona - Midfielder',
 'Young Boys - Midfielder',
 'Leipzig - Midfielder',
 'Celtic - Forward',
 'Bologna - Forward',
 'Milan - Defender',
 'Leipzig - Midfielder',
 'Salzburg - Goalkeeper',
 'Arsenal - Defender',
 'Salzburg - Midfielder',
 'PSV - Defender',
 'PSV - Forward',
 'Girona - Midfielder',
 'S. Bratislava - Midfielder',
 'S. Bratislava - Forward',
 'Leverkusen - Forward',
 'Girona - Midfielder',
 'Salzburg - Midfielder',
 'Sparta Praha - Forward',
 'Young Boys - Defender',
 'Sporting CP - Forward',
 'Bologna - Midfielder',
 'Girona - Defender',
 'Arsenal - Midfielder',
 'Lille - Defender',
 'Brest - Forward',
 'Salzburg - Forward',
 'Sporting CP - Midfielder',
 'Milan - Defender',
 'Atalanta - Midfielder',
 'Feyenoord - Forward',
 'Milan - Defender',
 'Aston Villa - Defender',
 'Young Boys - Midfielder',
 'Aston Villa - Forward',
 'Brest - Midfielder',
 'Man City - Midfielder',
 'Young Boys - Forward',
 'Juventus - Midfielder',
 'Lille - Midfielder',
 'Bologna - Defender',
 'Bayern München - Goalkeeper',
 'Sparta Praha - Midfielder',
 'Salzburg - Midfielder',
 'Barcelona - Midfielder',
 'Milan - Forward',
 'Young Boys - Forward',
 'B. Dortmund - Midfielder',
 'Arsenal - Midfielder',
 'Atalanta - Defender',
 'Sparta Praha - Defender',
 'Bayern München - Defender',
 'Monaco - Defender',
 'Sporting CP - Defender',
 'Bayern München - Midfielder',
 'Atalanta - Midfielder',
 'Atleti - Forward',
 'Shakhtar - Midfielder',
 'GNK Dinamo - Midfielder',
 'Bologna - Midfielder',
 'Monaco - Midfielder',
 'Man City - Defender',
 'S. Bratislava - Defender',
 'B. Dortmund - Defender',
 'Salzburg - Defender',
 'Young Boys - Midfielder',
 'Milan - Midfielder',
 'Milan - Defender',
 'Real Madrid - Defender',
 'Girona - Forward',
 'Feyenoord - Defender',
 'Sturm Graz - Defender',
 'Liverpool - Defender',
 'Barcelona - Defender',
 'Milan - Forward',
 'Girona - Forward',
 'B. Dortmund - Midfielder',
 'Leverkusen - Midfielder',
 'Aston Villa - Midfielder',
 'Atleti - Midfielder',
 'GNK Dinamo - Defender',
 'Young Boys - Defender',
 'Sparta Praha - Defender',
 'Crvena Zvezda - Goalkeeper',
 'GNK Dinamo - Goalkeeper',
 'Crvena Zvezda - Goalkeeper',
 'Juventus - Forward',
 'Leipzig - Defender',
 'GNK Dinamo - Midfielder',
 'Atalanta - Defender',
 'Real Madrid - Defender',
 'Leipzig - Defender',
 'Sparta Praha - Midfielder',
 'GNK Dinamo - Midfielder',
 'Atleti - Forward',
 'Feyenoord - Forward',
 'Benfica - Midfielder',
 'Aston Villa - Forward',
 'Leipzig - Midfielder',
 'PSV - Defender',
 'Lille - Forward',
 'Arsenal - Forward',
 'Brest - Defender',
 'S. Bratislava - Defender',
 'S. Bratislava - Midfielder',
 'Crvena Zvezda - Forward',
 'Bologna - Midfielder',
 'Girona - Midfielder',
 'Feyenoord - Defender',
 'Leverkusen - Forward',
 'Benfica - Forward',
 'Stuttgart - Midfielder',
 'Aston Villa - Forward',
 'Club Brugge - Defender',
 'Sporting CP - Defender',
 'Celtic - Midfielder',
 'B. Dortmund - Forward',
 'Liverpool - Forward',
 'Sporting CP - Midfielder',
 'B. Dortmund - Defender',
 'Young Boys - Forward',
 'Juventus - Defender',
 'Atleti - Defender',
 'Bologna - Defender',
 'Liverpool - Defender',
 'Lille - Defender',
 'Juventus - Forward',
 'GNK Dinamo - Defender',
 'Arsenal - Midfielder',
 'PSV - Defender',
 'Shakhtar - Forward',
 'Bologna - Defender',
 'Sporting CP - Defender',
 'GNK Dinamo - Midfielder',
 'Leverkusen - Forward',
 'Bologna - Midfielder',
 'Atalanta - Defender',
 'Monaco - Midfielder',
 'Celtic - Defender',
 'Shakhtar - Defender',
 'Juventus - Goalkeeper',
 'Juventus - Defender',
 'Paris - Forward',
 'Juventus - Midfielder',
 'Shakhtar - Midfielder',
 'Inter - Forward',
 'Salzburg - Midfielder',
 'S. Bratislava - Forward',
 'Sporting CP - Midfielder',
 'Arsenal - Defender',
 'S. Bratislava - Defender',
 'GNK Dinamo - Forward',
 'Man City - Midfielder',
 'Sturm Graz - Midfielder',
 'GNK Dinamo - Forward',
 'Sturm Graz - Midfielder',
 'Club Brugge - Midfielder',
 'Feyenoord - Defender',
 'Crvena Zvezda - Midfielder',
 'Milan - Forward',
 'Real Madrid - Defender',
 'Brest - Defender',
 'Leipzig - Goalkeeper',
 'Paris - Goalkeeper',
 'Sporting CP - Goalkeeper',
 'Man City - Goalkeeper',
 'Sturm Graz - Goalkeeper',
 'Monaco - Goalkeeper',
 'Real Madrid - Goalkeeper',
 'Crvena Zvezda - Goalkeeper',
 'Crvena Zvezda - Defender',
 'Feyenoord - Forward',
 'Club Brugge - Forward',
 'Real Madrid - Defender',
 'Bayern München - Midfielder',
 'Sporting CP - Defender',
 'Crvena Zvezda - Midfielder',
 'Liverpool - Forward',
 'Sporting CP - Forward',
 'PSV - Forward',
 'Shakhtar - Defender',
 'Lille - Midfielder',
 'Sparta Praha - Midfielder',
 'Sparta Praha - Defender',
 'Juventus - Defender',
 'Crvena Zvezda - Midfielder',
 'Stuttgart - Defender',
 'Benfica - Defender',
 'S. Bratislava - Forward',
 'Crvena Zvezda - Forward',
 'Leipzig - Forward',
 'Celtic - Midfielder',
 'Salzburg - Defender',
 'PSV - Forward',
 'Girona - Forward',
 'PSV - Defender',
 'Stuttgart - Midfielder',
 'S. Bratislava - Midfielder',
 'Benfica - Midfielder',
 'Shakhtar - Forward',
 'Atleti - Midfielder',
 'Real Madrid - Midfielder',
 'Paris - Defender',
 'Crvena Zvezda - Midfielder',
 'Club Brugge - Midfielder',
 'Liverpool - Defender',
 'Aston Villa - Defender',
 'Stuttgart - Forward',
 'Young Boys - Forward',
 'Lille - Forward',
 'Real Madrid - Forward',
 'Sturm Graz - Midfielder',
 'Shakhtar - Defender',
 'Stuttgart - Defender',
 'Leverkusen - Midfielder',
 'Sturm Graz - Forward',
 'Sparta Praha - Midfielder',
 'Bologna - Forward',
 'Leverkusen - Defender',
 'Atalanta - Forward',
 'Aston Villa - Defender',
 'Feyenoord - Goalkeeper',
 'Atalanta - Midfielder',
 'Leverkusen - Forward',
 'Shakhtar - Midfielder',
 'Arsenal - Defender',
 'Liverpool - Defender',
 'Aston Villa - Midfielder',
 'Club Brugge - Forward',
 'Paris - Defender',
 'Lille - Defender',
 'Celtic - Midfielder',
 'Atleti - Defender',
 'Man City - Defender',
 'Monaco - Forward',
 'Feyenoord - Midfielder',
 'S. Bratislava - Midfielder',
 'Benfica - Defender',
 'Leverkusen - Defender',
 'Man City - Midfielder',
 'Liverpool - Forward',
 'PSV - Midfielder',
 'Leverkusen - Forward',
 'Bayern München - Defender',
 'Milan - Forward',
 'Juventus - Defender',
 'Aston Villa - Midfielder',
 'Girona - Midfielder',
 'Benfica - Defender',
 'Sturm Graz - Forward',
 'Man City - Forward',
 'Juventus - Defender',
 'Girona - Midfielder',
 'Stuttgart - Defender',
 'Monaco - Forward',
 'Benfica - Forward',
 'Feyenoord - Midfielder',
 'Bayern München - Forward',
 'Salzburg - Forward',
 'Crvena Zvezda - Defender',
 'Man City - Midfielder',
 'Salzburg - Midfielder',
 'Liverpool - Midfielder',
 'PSV - Midfielder',
 'Man City - Midfielder',
 'Sparta Praha - Defender',
 'Sparta Praha - Defender',
 'Brest - Defender',
 'Girona - Defender',
 'Man City - Defender',
 'B. Dortmund - Goalkeeper',
 'Bayern München - Goalkeeper',
 'Bologna - Goalkeeper',
 'Atalanta - Goalkeeper',
 'Stuttgart - Goalkeeper',
 'Inter - Goalkeeper',
 'PSV - Goalkeeper',
 'Girona - Goalkeeper',
 'Arsenal - Goalkeeper',
 'Barcelona - Goalkeeper',
 'Brest - Goalkeeper',
 'Sparta Praha - Midfielder',
 'Crvena Zvezda - Midfielder',
 'Leipzig - Forward',
 'Celtic - Forward',
 'Shakhtar - Midfielder',
 'Brest - Defender',
 'Salzburg - Defender',
 'Liverpool - Forward',
 'Feyenoord - Forward',
 'Feyenoord - Forward',
 'Girona - Midfielder',
 'Lille - Midfielder',
 'Brest - Midfielder',
 'B. Dortmund - Midfielder',
 'Benfica - Forward',
 'Milan - Midfielder',
 'Sporting CP - Midfielder',
 'GNK Dinamo - Midfielder',
 'Club Brugge - Defender',
 'Sporting CP - Forward',
 'Brest - Forward',
 'Monaco - Defender',
 'Atalanta - Defender',
 'Feyenoord - Forward',
 'Celtic - Defender',
 'GNK Dinamo - Forward',
 'Celtic - Midfielder',
 'Milan - Defender',
 'Benfica - Forward',
 'Stuttgart - Defender',
 'Club Brugge - Forward',
 'Monaco - Midfielder',
 'Salzburg - Midfielder',
 'Barcelona - Forward',
 'Barcelona - Defender',
 'Celtic - Midfielder',
 'Sparta Praha - Midfielder',
 'Paris - Midfielder',
 'Feyenoord - Midfielder',
 'Atleti - Midfielder',
 'Sporting CP - Midfielder',
 'Salzburg - Defender',
 'Lille - Defender',
 'Bologna - Defender',
 'Bayern München - Goalkeeper',
 'Sparta Praha - Forward',
 'Leipzig - Defender',
 'Barcelona - Forward',
 'Young Boys - Midfielder',

#### Let's Set Up a DataFrame for the Qualitative Information

In [14]:
data = pd.DataFrame({
        'Player_Name': player_name,
        'Team'       : team,
        'Position'   : team,
        })
data.shape

(1107, 3)

In [15]:
data.head(8)

   Player_Name                Team            Position
0        Pacho    Paris - Defender    Paris - Defender
1       Hakimi    Paris - Defender    Paris - Defender
2  Nuno Mendes    Paris - Defender    Paris - Defender
3      Vitinha  Paris - Midfielder  Paris - Midfielder
4   Marquinhos    Paris - Defender    Paris - Defender
5   João Neves  Paris - Midfielder  Paris - Midfielder
6   Donnarumma  Paris - Goalkeeper  Paris - Goalkeeper
7       Sommer  Inter - Goalkeeper  Inter - Goalkeeper

#### We should perform some error handling and processing

In [16]:
position_list = []

for index, item in enumerate(team):
    try:
        processed_item = item.split("-")[1].strip()
        position_list.append(processed_item)
    except Exception as e:
        processed_item = "!!!!!!!!!"
        position_list.append(processed_item)
        print(f"Error at index {index}: {e}, item: '{item}'")

In [17]:
len(position_list)

1107

In [18]:
# Let's make sure that Team and Position Columns are accurate 

Numerical_Data['Player_Name'] = np.array([i for i in player_name])
Numerical_Data['Team'] = np.array([i.split("-")[0].strip() for i in team])
Numerical_Data['Position'] = np.array([i for i in position_list])

C:\Users\18126\AppData\Local\Temp\ipykernel_26912\1375059972.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Numerical_Data['Player_Name'] = np.array([i for i in player_name])

In [19]:
Numerical_Data.columns

Index(['Minutes_played', 'Matches', 'Goals', 'Assists', 'Distance_covered',
       'Top_speed', 'Player_Name', 'Team', 'Position'],
      dtype='object')

In [20]:
# Let's compile both qualitative and quantitative data

Combined_Data = Numerical_Data[['Player_Name', 'Team', 'Position', 
                                'Minutes_played', 'Matches', 'Goals', 
                                'Assists', 'Distance_covered','Top_speed']]
Combined_Data.head()

,Player_Name,Team,Position,Minutes_played,Matches,Goals,Assists,Distance_covered,Top_speed
0,Pacho,Paris,Defender,1542,17,0,0,159.2,33.8
1,Hakimi,Paris,Defender,1540,17,4,5,176.8,36.9
2,Nuno Mendes,Paris,Defender,1449,16,4,2,145.4,35.7
3,Vitinha,Paris,Midfielder,1448,17,2,2,180.2,32.3
4,Marquinhos,Paris,Defender,1439,16,0,0,158.1,33.2

In [21]:
# Show rows where either Player Name, Team, or Position is empty

empty_player_name = Combined_Data[Combined_Data['Player_Name'].isna()]
empty_team        = Combined_Data[Combined_Data['Team'].isna()]
empty_position    = Combined_Data[Combined_Data['Position'].isna()]

print(f'Number of rows with an empty player name: {len(empty_player_name)}')
print(f'Number of rows with an empty team value: {len(empty_team)}')
print(f'Number of rows with an empty position value: {len(empty_position)}')

Number of rows with an empty player name: 0
Number of rows with an empty team value: 0
Number of rows with an empty position value: 0

In [22]:
# Let's see if there are any positions other than the only 4 that should be there

valid_positions = ['Goalkeeper', 'Defender', 'Midfielder', 'Forward']
invalid_position_rows = Combined_Data[~Combined_Data['Position'].isin(valid_positions)]

invalid_position_rows

Empty DataFrame
Columns: [Player_Name, Team, Position, Minutes_played, Matches, Goals, Assists, Distance_covered, Top_speed]
Index: []

In [23]:
# Let's Convert the names to ASCII format, which makes it more suitable for regression

Combined_Data['Player_Name'] = Combined_Data['Player_Name'].apply(unidecode.unidecode)
Combined_Data['Team'] = Combined_Data['Team'].apply(unidecode.unidecode)

In [24]:
Combined_Data.head(10)

,Player_Name,Team,Position,Minutes_played,Matches,Goals,Assists,Distance_covered,Top_speed
0,Pacho,Paris,Defender,1542,17,0,0,159.2,33.8
1,Hakimi,Paris,Defender,1540,17,4,5,176.8,36.9
2,Nuno Mendes,Paris,Defender,1449,16,4,2,145.4,35.7
3,Vitinha,Paris,Midfielder,1448,17,2,2,180.2,32.3
4,Marquinhos,Paris,Defender,1439,16,0,0,158.1,33.2
5,Joao Neves,Paris,Midfielder,1435,17,1,1,184.3,31.7
6,Donnarumma,Paris,Goalkeeper,1380,15,0,0,71.7,26.1
7,Sommer,Inter,Goalkeeper,1290,14,0,0,50.5,25.2
8,Kimmich,Bayern Munchen,Midfielder,1260,14,0,6,178.9,32.2
9,Valverde,Real Madrid,Midfielder,1236,14,0,3,140,35.2

#### We can save our model now

In [ ]:
# Let's create a Data folder to store the data in
Data_Folder= 'Data'

if not os.path.exists(Data_Folder):
    os.makedirs(Data_Folder)

# Now we can save the model in the newly created folder
file_path = os.path.join(Data_Folder, f'UEFA Stats {year_of_interest}.xlsx')

Combined_Data.to_excel(file_path, index=False, header=True)

print(f'The file was saved to {file_path}')
# Last Comment 12

The file was saved to Data\UEFA Stats 2025.xlsx